version: '3.8'

services:
  app:
    build: .
    container_name: train-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/train
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ASDzxc123#
    networks:
      - app-network

  db:
    image: mysql:8.0.1
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ASDzxc123#
      MYSQL_DATABASE: train
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
